In [19]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import balanced_accuracy_score,precision_score,recall_score,f1_score, roc_auc_score

In [20]:
df = pd.read_csv('data/crawler/unified-events-statistics.csv')
df = df.replace(['BLUE: first_blood',
    'BLUE: dragon',
    'BLUE: herald',
    'BLUE: first_tower_top',
    'BLUE: first_tower_mid',
    'BLUE: first_tower_bot',
    'BLUE: second_tower_top',
    'BLUE: second_tower_mid',
    'BLUE: second_tower_bot',
    'BLUE: third_tower_top',
    'BLUE: third_tower_mid',
    'BLUE: third_tower_bot',
    'BLUE: inhibitor_top',
    'BLUE: inhibitor_mid',
    'BLUE: inhibitor_bot',
    'BLUE: baron',
    'BLUE: elder_dragon',
    'BLUE: nexus_tower',
    'BLUE: nexus',
    'RED: first_blood',
    'RED: dragon',
    'RED: herald',
    'RED: first_tower_top',
    'RED: first_tower_mid',
    'RED: first_tower_bot',
    'RED: second_tower_top',
    'RED: second_tower_mid',
    'RED: second_tower_bot',
    'RED: third_tower_top',
    'RED: third_tower_mid',
    'RED: third_tower_bot',
    'RED: inhibitor_top',
    'RED: inhibitor_mid',
    'RED: inhibitor_bot',
    'RED: baron',
    'RED: elder_dragon',
    'RED: nexus_tower',
    'RED: nexus'], range(38))
# validation_df = df.apply(lambda row: row[df['game'].isin(validation_games)])
# df = df[~df.game.isin(validation_games)]
df.head()

,golId,game,event1,event2,event3,event4,event5,event6,event7,event8,event9,event10,event11,event12,event13,event14,event15,event16,event17,event18,event19,event20,event21,event22,event23,event24,event25,event26,event27,event28,event29,event30,event31,event32,event33,event34,event35,event36,event37,event38,event39,event40,event41,event42,event43,event44,event45,blueTopGP,blueTopWR,blueTopKDA,blueJungleGP,blueJungleWR,blueJungleKDA,blueMidGP,blueMidWR,blueMidKDA,blueADCGP,blueADCWR,blueADCKDA,blueSupportGP,blueSupportWR,blueSupportKDA,redTopGP,redTopWR,redTopKDA,redJungleGP,redJungleWR,redJungleKDA,redMidGP,redMidWR,redMidKDA,redAdcGP,redAdcWR,redAdcKDA,redSupportGP,redSupportWR,redSupportKDA,result
0,36889,ESPORTSTMNT02_2557053,19,1,2,5,1,20,21,4,1,3,34,23,26,6,24,1.0,8.0,7.0,22.0,15.0,10.0,13.0,35.0,29.0,32.0,27.0,30.0,11.0,14.0,17.0,17.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,0.00,0.9,0,0.0,0.0,1,1.0,5.0,3,0.67,6.7,3,0.67,4.8,0,0.0,0.0,0,0.0,0.0,0,0.0,0.0,1,0.00,0.4,0,0.0,0.0,1
1,36908,ESPORTSTMNT02_2577492,0,20,2,1,24,4,2,5,22,23,1,27,34,3,20,34.0,20.0,25.0,20.0,34.0,26.0,29.0,32.0,36.0,36.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,0.67,5.0,1,0.0,0.7,1,1.0,9.0,0,0.00,0.0,0,0.00,0.0,2,0.0,2.8,0,0.0,0.0,0,0.0,0.0,1,1.00,12.0,2,0.5,3.8,0
2,36932,ESPORTSTMNT05_2530954,19,2,20,5,1,2,3,4,1,7,15,8,11,14,17,17.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.00,0.0,0,0.0,0.0,5,0.6,4.7,0,0.00,0.0,0,0.00,0.0,1,0.0,0.0,0,0.0,0.0,0,0.0,0.0,2,0.00,1.7,0,0.0,0.0,1
3,36933,ESPORTSTMNT05_2530886,0,21,20,22,24,21,20,3,27,4,23,34,7,25,26,28.0,31.0,29.0,32.0,30.0,33.0,36.0,20.0,36.0,37.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0.00,0.0,0,0.0,0.0,1,0.0,0.2,0,0.00,0.0,0,0.00,0.0,3,1.0,4.1,2,0.5,11.7,0,0.0,0.0,2,1.00,31.0,1,1.0,4.7,0
4,36953,ESPORTSTMNT02_2556972,0,21,1,5,2,24,1,4,22,23,20,15,3,7,10,1.0,8.0,15.0,6.0,13.0,17.0,17.0,18.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,0.50,2.2,1,0.0,0.5,0,0.0,0.0,0,0.00,0.0,0,0.00,0.0,1,0.0,2.0,1,0.0,1.6,1,0.0,1.4,3,0.33,3.3,0,0.0,0.0,1

In [21]:
y = df['result'].copy()
X = df.drop(['golId','result','game','event11','event12','event13','event14','event15','event16','event17','event18','event19','event20','event21','event22','event23','event24','event25','event26','event27','event28','event29','event30','event31','event32','event33','event34','event35','event36','event37','event38','event39','event40','event41','event42','event43','event44','event45','blueTopGP','blueTopWR','blueTopKDA','blueJungleGP','blueJungleWR','blueJungleKDA','blueMidGP','blueMidWR','blueMidKDA','blueADCGP','blueADCWR','blueADCKDA','blueSupportGP','blueSupportWR','blueSupportKDA','redTopGP','redTopWR','redTopKDA','redJungleGP','redJungleWR','redJungleKDA','redMidGP','redMidWR','redMidKDA','redAdcGP','redAdcWR','redAdcKDA','redSupportGP','redSupportWR','redSupportKDA'],axis=1)
X.head()

,event1,event2,event3,event4,event5,event6,event7,event8,event9,event10
0,19,1,2,5,1,20,21,4,1,3
1,0,20,2,1,24,4,2,5,22,23
2,19,2,20,5,1,2,3,4,1,7
3,0,21,20,22,24,21,20,3,27,4
4,0,21,1,5,2,24,1,4,22,23

In [22]:
def preprocess_input(X,y):
    X = X.copy()
    X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.8,random_state=42, stratify=y)
    scaler = StandardScaler()   
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)
    return X_train,X_test,y_train,y_test
X_train,X_test,y_train,y_test = preprocess_input(X,y)

In [23]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC, SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier

models = {
    'Logistic Regression': LogisticRegression(random_state=42,max_iter=50000),
    'Support Vector Machine (Linear Kernel)': LinearSVC(random_state=42,max_iter=50000),
    'Support Vector Machine (RBF Kernel)': SVC(random_state=42,C=100,gamma=0.001,kernel='rbf',max_iter=50000),
    'Decission Tree': DecisionTreeClassifier(random_state=42),
    'Adaboost': AdaBoostClassifier(random_state=42),
    'Random Forest': RandomForestClassifier(random_state=42,max_depth=25,n_estimators=600,min_samples_split=2,min_samples_leaf=1),
    'Gradient Boosting Classifier': GradientBoostingClassifier(random_state=42,criterion='friedman_mse',learning_rate=0.025,loss='deviance',max_depth=4,max_features='log2',min_samples_leaf=8,min_samples_split=3, n_estimators=100,subsample=0.5)
}


for name, model in models.items():
  model.fit(X_train,y_train)
  print(name + ' trained')

Logistic Regression trained
Support Vector Machine (Linear Kernel) trained
Support Vector Machine (RBF Kernel) trained
Decission Tree trained
Adaboost trained
Random Forest trained
Gradient Boosting Classifier trained

In [24]:
scores_list = []

for name,model in models.items():    
    scores_list.append({
    'Model': name,
    'Balanced Accuracy': balanced_accuracy_score(y_test,model.predict(X_test)),
    'Precision':  precision_score(y_test,model.predict(X_test)),
    'Recall': recall_score(y_test,model.predict(X_test)),
    'F1-Score': f1_score(y_test,model.predict(X_test)),
    'ROC/AUC Score': roc_auc_score(y_test,model.predict(X_test))
    })
scores = pd.DataFrame(scores_list)

In [25]:
scores

,Model,Balanced Accuracy,Precision,Recall,F1-Score,ROC/AUC Score
0,Logistic Regression,0.799335,0.800000,0.780488,0.790123,0.799335
1,Support Vector Machine (Linear Kernel),0.811530,0.804878,0.804878,0.804878,0.811530
2,Support Vector Machine (RBF Kernel),0.811530,0.804878,0.804878,0.804878,0.811530
3,Decission Tree,0.715632,0.729730,0.658537,0.692308,0.715632
4,Adaboost,0.822894,0.825000,0.804878,0.814815,0.822894
5,Random Forest,0.774113,0.805556,0.707317,0.753247,0.774113
6,Gradient Boosting Classifier,0.797672,0.833333,0.731707,0.779221,0.797672

In [26]:
import pickle

with open("../models/model-3.pkl", "wb") as f:
    pickle.dump(models['Random Forest'], f)

FileNotFoundError: [Errno 2] No such file or directory: '../models/model-3.pkl'